### ISSUE TITLE
Alternative MaybeT instance might not be distributive

### ISSUE THREAD

**Issue by LukaJCB** [purescript/purescript-transformers#116]
Imagine this scenario:

```haskell
f :: MaybeT Effect (a -> b)
f = empty 
g :: MaybeT Effect (a -> b)
x :: MaybeT Effect a

-- Will run the effects of x only once
(f <|> g) <*> x

-- Will run the effects of x twice
 (f <*> x) <|> (g <*> x)
```

**Comment by hdgarrood** [comment]
Thanks for the report. This does indeed seem problematic. Perhaps we should just remove the Alternative instance in the next breaking release.

**Comment by mhmdanas** [comment]
After this library is updated to 0.14, can I make a PR for this? Or do we not breaking release for now?

**Comment by JordanMartinez** [comment]
We're doing breaking changes now, not later.

**Comment by hdgarrood** [comment]
Actually, I think we should leave this as-is. Many Alternative instances in the wild obey a "left catch" law:
> `pure a <|> b = pure a`

instead of the documented distributivity law, and MaybeT is one example. Other examples include parsers and Aff. See also https://github.com/purescript/purescript-control/issues/63 - I think we should wait until we've made progress there before removing any instances here.

**Comment by hdgarrood** [comment]
I think this is just one example of the issue described in https://github.com/purescript/purescript-control/issues/63, so I think we should close this for now and continue tracking the issue there.
