### ISSUE TITLE
Do we need `ErrorT` now we have `Except`?

### ISSUE THREAD

**Issue by garyb** [purescript/purescript-transformers#45]

**Comment by hdgarrood** [comment]
The only reason we might need it, as far as I can tell, is if existing code relied on it. Perhaps we can deprecate it and remove it in the next release?

**Comment by garyb** [comment]
Sounds good to me. @paf31?

**Comment by paf31** [comment]
Well, the only thing that differs, as I understand it, is the `MonadPlus` instance. Instead of an `Error` constraint (which gives an error for `mempty`), we use a `Monoid` constraint, which gives an empty error and a way of combining parallel errors. I can't think of a case where you wouldn't be able to use `ExceptT`, and using the `First` monoid gives a smooth transition I think. So I say :+1:

**Comment by hdgarrood** [comment]
I think this can be closed now?

**Comment by garyb** [comment]
Yep!
