### ISSUE TITLE
callCC type signature?

### ISSUE THREAD

**Issue by jqyu** [purescript/purescript-transformers#73]
Pardon my ignorance if I'm misunderstanding what a Cont transformer is, but is there a reason why the [`callCC` type signature](https://github.com/purescript/purescript-transformers/blob/master/src/Control/Monad/Cont/Class.purs#L25) is

```purs
callCC :: forall a b. ((a -> m b) -> m a) -> m a
```

Rather than the more general:

```purs
callCC :: forall a. (forall b. (a -> m b) -> m a) -> m a
```

I recently tried to write some code that looked like:
```purs
value = callCC \return -> do
  foo <- foo' `fallBackTo` return defaultValue
  bar <- bar' `fallBackTo` return defaultValue
  fn foo bar
```
Which failed to type check because `foo` and `bar` had different types, so the signature of `return` wasn't happy.

**Comment by garyb** [comment]
I think it's probably fine to move the `forall` up like that, since the use of `b` here is only in the return type anyway (because we don't care about the result value).

It's probably the way it is now because it's the same in Haskell, and a lot of stuff was borrowed or straight lifted from there at first. I assume it's this way in Haskell to avoid the need of `-XRank2Types`/`-XRankNTypes`.

**Comment by jqyu** [comment]
Hmm, tried actually implementing it and it's much easier said than done. Although the instance declarations for the other monad transformers like `ExceptT`, `MaybeT`, `StateT`, and `WriterT` should work as-is, they fail to typecheck.

The [`liftCallCC` functions](http://hub.darcs.net/ross/transformers/browse/Control/Monad/Trans/Except.hs#282) are pretty hard to translate using rank 2 types. Going to have to put some more thought into this before submitting a PR
